live-composer/live-composer-page-builder

ds-live-composer.php, includes/archive-templates.php, includes/plugin-options-framework/inc/access-control.php, includes/plugin-options-framework/inc/display-options.php, includes/plugin-options-framework/inc/init.php, includes/plugin-options-framework/inc/options.php, includes/plugin-options-framework/inc/performance.php, includes/plugin-options-framework/plugin-options-framework.php, includes/styling-presets.php, modules/navigation/functions.php, modules/widgets/functions.php
Options in admin area not linked to it's parent section
=> LC 1.0.8 - menu moving fix

includes/post-templates.php
Looks like we get some internal errors after this merge. We will take sometime over the week to review it and re-merge again.
Thank you.
=> Revert "Run dslc_post_templates_init later"

modules/blog/module.php, modules/galleries/functions.php, modules/galleries/module.php, modules/infobox/module.php, modules/partners/module.php, modules/posts/module.php, modules/projects/module.php, modules/staff/module.php, modules/testimonials/module.php, modules/tp-comments/module.php, modules/woocommerce/module.php
@livecomposer requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/livecomposer/Live-Composer/
=> Scrutinizer Auto-Fixes

includes/options.extension.class.php, includes/plugin-options-framework/inc/init.php, includes/plugin-options-framework/options-extension-template.php
- Std handler
- WP styled class methods & vars
=> LC1.0.8: added std handler for dslc_get_c_option

includes/post-options-framework/post-options-framework.php
- if value is set to '0' it changed to opt[std], bug fixed
=> LC1: post options framework options display bug fixed

includes/display-functions.php, includes/row-system/inc/options-output.php, includes/row-system/inc/options.php, js/builder.main.js
- row custom class filter
- row colorpicker lazy load
- row slider changed
=> LC1.1: row fixes

includes/container.class.php, includes/display-functions.php, includes/module_area.class.php, includes/row.class.php, includes/wrapper.class.php
Added:
- DSLC_Container
- DSLC_Row
- DSLC_Module_Area
- DSLC_Wrapper
=> LC1.1: Added DSLC_Container class, etc

ds-live-composer.php, includes/display-functions.php, includes/display.class.php, includes/other-functions.php, includes/post-options-framework/post-options-framework.php, includes/scripts.php, js/builder.main.js, js/classes/ModuleSortArea.js, js/main.js
- New DSLC_Display class
- DSLC_Display::show_lc_button_on_front
- JS Module Area class
- LC activation button func
=> LC1.1[frame]: additions in details

includes/display-functions.php, includes/scripts.php, js/builder.main.js, js/classes/Module.js, js/classes/ModuleSortArea.js, js/editor.frame.js, js/libs/mq-mutation-observer.js
- Mutation observer for Module Area class changes
- Separated Module Area, iframe & builder.main
- 'Disable' LC button fixed
=> LC1.1[frame]: added funcs

includes/display-functions.php, includes/scripts.php, js/builder-modal-window/builder.modalwindow.functions.js, js/builder-module/builder.module.functions.js, js/builder-settings-panel/builder.settings.panel.functions.js, js/builder-ui-general/builder.uigeneral.functions.js
=> LC1.1[frame]: fixes continue

js/builder/builder.settings.panel.functions.js, js/builder/builder.uigeneral.functions.js, js/builder/builder.util.functions.js
=> Tiny mce inline editor

includes/display-functions.php, includes/editorinterface.class.php, includes/functions.php, includes/header-footer.php, includes/post-options-framework/post-options-framework.php, includes/single-templates-framework/inc/filters.php, includes/single-templates-framework/inc/functions.php
– Fix bug 'Can Only Use 2 Templates' issue #131
– Introduced dslc_current_user_can( 'save' ) function
=> – Fix bug 'Can Only Use 2 Templates' issue #131

includes/other.php
Fix issue #159: Icon selection control is broken
=> Fix issue #159: Icon selection control is broken

includes/scripts.php, js/builder/builder.uigeneral.functions.js
=> - Loading app after tinyMCE sripts added into preview area

js/builder/builder.module.functions.js, js/builder/builder.plugins.js, js/builder/builder.settings.panel.functions.js
#249 
- Added error when MutationObserver not supported
- Added paste plugin to tinyMCE
=> - Fixed inline-editor paste bug

modules/staff/functions.php, modules/staff/module.php
Title says it all! :) 
Instagram is a popular social platform and already had CSS icon support.  This PR simply adds the option to the staff module's `functions.php` and supporting HTML to `module.php`
=> Add Instagram as a social option to staff module

includes/css-generation.php, readme.txt
* Issue [#368](https://github.com/livecomposer/live-composer-page-builder/issues/368): Border hover on buttons not working
=> * Issue [#368]

modules/accordion/module.php
=> Accordion element radius missing

modules/social/module.php
=> Add VK to the Social module

js/builder/builder.settings.panel.functions.js
=> H1 is missing from front-end formats options

css/builder/builder.main.css, js/builder/builder.uigeneral.functions.js
=> Improve - exclude from main listing

css/frontend/modules.css
=> Tabs - Borders Color

includes/options.extension.class.php
=> Improve: Class Options Extension

includes/shortcodes.php
fixed: Security vulnerability in dslc notification short code output.
=> fixed: security vulnerability in short code output
